// Generated by LiveScript 1.2.0
(function(){
  var Decoration, UserDecorator, userDecorator;
  require('../test_setup');
  Decoration = require('../../client_decorator');
  Decoration = require('../../decoration');
  UserDecorator = (function(superclass){
    var prototype = extend$((import$(UserDecorator, superclass).displayName = 'UserDecorator', UserDecorator), superclass).prototype, constructor = UserDecorator;
    UserDecorator.setter('fullName').on('firstName', 'lastName', function(){
      return this.fullName = [this.firstName, this.lastName].join(' ');
    });
    function UserDecorator(model, context){
      this.model = model;
      this.context = context;
      UserDecorator.superclass.apply(this, arguments);
    }
    prototype.decorate = function(){
      return superclass.prototype.decorate;
    };
    return UserDecorator;
  }(ClientDecorator));
  userDecorator = new UserDecorator;
  describe('Decoration', function(){
    var decoration;
    decoration = null;
    before(function(){
      return decoration = new Decoration();
    });
    specify('creates a decoration', function(){
      return decoration.should.be.an.instanceOf(Decoration);
    });
    return describe('decorate', function(){
      before(function(){
        var decoration, decorated;
        Decoration.add(userDecorator, 'user');
        decoration = new Decoration(obj, model);
        return decorated = decoration.decorateFor(context);
      });
      return specify('creates a decoration', function(){
        return decoration.should.be.an.instanceOf(Decoration);
      });
    });
  });
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
