// Generated by LiveScript 1.2.0
(function(){
  var UserSerializer;
  UserSerializer = (function(superclass){
    var prototype = extend$((import$(UserSerializer, superclass).displayName = 'UserSerializer', UserSerializer), superclass).prototype, constructor = UserSerializer;
    function UserSerializer(model, context){
      this.model = model;
      this.context = context;
      UserSerializer.superclass.apply(this, arguments);
    }
    return UserSerializer;
  }(ServerSerializer));
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
