// Generated by LiveScript 1.2.0
(function(){
  var requires;
  requires = require('./requires');
  module.exports = {
    DecoratorMw: requires.lib('decorator_mw'),
    Decorations: requires.lib('decorations'),
    CtxDecorations: requires.lib('context_decorations'),
    BaseModel: requires.lib('base_model')
  };
}).call(this);
