// Generated by LiveScript 1.2.0
(function(){
  var _, underscore, fullPath, libPath, testPath, classPath, slice$ = [].slice;
  require('sugar');
  _ = require('prelude-ls');
  underscore = function(){
    var items, strings;
    items = slice$.call(arguments);
    items = items.flatten();
    strings = items.map(function(item){
      return String(item);
    });
    return _.map(function(it){
      return it.underscore();
    }, strings);
  };
  fullPath = function(base){
    var paths, upaths;
    paths = slice$.call(arguments, 1);
    upaths = underscore.apply(null, paths);
    return ['.', base, upaths].flatten().join('/');
  };
  libPath = function(base){
    var paths, upaths;
    paths = slice$.call(arguments, 1);
    upaths = underscore.apply(null, paths);
    return ['./lib', base, upaths].flatten().join('/');
  };
  testPath = function(){
    var paths;
    paths = slice$.call(arguments);
    return fullPath.apply(null, ['test'].concat(slice$.call(paths)));
  };
  classPath = function(){
    var paths;
    paths = slice$.call(arguments);
    return fullPath.apply(null, ['classes'].concat(slice$.call(paths)));
  };
  module.exports = {
    test: function(){
      var paths;
      paths = slice$.call(arguments);
      return require(testPath.apply(null, paths));
    },
    clazz: function(){
      var paths;
      paths = slice$.call(arguments);
      return this.fixture('classes', paths);
    },
    fixture: function(){
      var paths;
      paths = slice$.call(arguments);
      return this.test('fixtures', paths);
    },
    file: function(){
      var paths;
      paths = slice$.call(arguments);
      return require(fullPath(paths));
    },
    lib: function(){
      var paths;
      paths = slice$.call(arguments);
      return require(libPath(paths));
    },
    mw: function(){
      var paths;
      paths = slice$.call(arguments);
      return require(libPath('mw', paths));
    },
    m: function(path){
      return this.file(path);
    },
    files: function(){
      var paths;
      paths = slice$.call(arguments);
      return paths.flatten().map(function(path){
        return this.file(path);
      });
    },
    fixtures: function(){
      var paths;
      paths = slice$.call(arguments);
      return paths.flatten().map(function(path){
        return this.fixture(path);
      });
    },
    tests: function(){
      var paths;
      paths = slice$.call(arguments);
      return paths.flatten().map(function(path){
        return this.test(path);
      });
    }
  };
}).call(this);
