// Generated by LiveScript 1.2.0
(function(){
  var rek, requires, Class, BaseModel;
  rek = require('rekuire');
  requires = rek('requires');
  Class = require('jsclass/src/core').Class;
  BaseModel = requires.file('base_model');
  module.exports = new Class(BaseModel, {
    initialize: function(obj){
      return this.callSuper();
    },
    fullName: function(){
      return [this.firstName, this.lastName].join(' ');
    }
  });
}).call(this);
