// Generated by LiveScript 1.2.0
(function(){
  var Class, _, Base;
  Class = require('jsclass/src/core').Class;
  _ = require('prelude-ls');
  Base = new Class({
    initialize: function(obj){
      var self;
      if (obj === void 8) {
        return;
      }
      if (!_.isType('Object', obj)) {
        throw Error("Must be an Object, was: " + obj);
      }
      self = this;
      _.keys(obj).each(function(key){
        return self[key] = obj[key];
      });
      return this;
    }
  });
  module.exports = Base;
}).call(this);
