// Generated by LiveScript 1.2.0
(function(){
  var Class, Module, Hash;
  Class = require('jsclass/src/core').Class;
  Module = require('jsclass/src/core').Module;
  Hash = require('jsclass/src/core').Hash;
  module.exports = new Class({
    initialize: function(decorations){
      this.repository = new Hash;
      if (decorations === void 8) {
        return;
      }
      if (!_.isType('Object', decorations)) {
        throw Error("Must be an Object, was : " + typeof klass + " :: " + decorations);
      }
      return decorations.each(function(name, dec){
        return this.set(name, dec);
      });
    },
    get: function(modelName){
      return this.repository.get(modelName);
    },
    set: function(modelName, klass){
      if (!_.isType('Function', klass)) {
        throw Error("klass to be set must be a Function, was: " + typeof klass + " :: " + klass);
      }
      return this.repository.set(modelName, klass);
    }
  });
}).call(this);
