// Generated by LiveScript 1.2.0
(function(){
  var _, Decoration;
  _ = require("lodash");
  module.exports = Decoration = (function(){
    Decoration.displayName = 'Decoration';
    var prototype = Decoration.prototype, constructor = Decoration;
    Decoration.decorators = {};
    Decoration.add = function(objDecorator, name){
      name || (name = objDecorator.name);
      return this.decorators[name] = objDecorator;
    };
    function Decoration(object, name){
      this.object = object;
      this.name = name;
    }
    prototype.decorateFor = function(context){
      var decorator, decoratedObj, customized;
      decorator = this.decorators[this.name](context);
      decoratedObj = _.extend({}, this.object, decorator.blueprint);
      customized = decorator.customizeFor(context);
      return _.extend(decoratedObj, customized);
    };
    return Decoration;
  }());
}).call(this);
