// Generated by LiveScript 1.2.0
(function(){
  var classToType, i$, ref$, len$, name;
  classToType = {};
  for (i$ = 0, len$ = (ref$ = "Boolean Number String Function Array Date RegExp Undefined Null".split(" ")).length; i$ < len$; ++i$) {
    name = ref$[i$];
    classToType["[object " + name + "]"] = name.toLowerCase();
  }
  module.exports = function(obj){
    var strType;
    strType = Object.prototype.toString.call(obj);
    return classToType[strType] || "object";
  };
}).call(this);
