// Generated by LiveScript 1.2.0
(function(){
  var requires, assert, expect, _, Person, DecoratorMw, OrderedHash, Decorations, CtxDecorations;
  requires = require('../../requires');
  requires.test('test_setup');
  assert = require('chai').assert;
  expect = require('chai').expect;
  _ = require('prelude-ls');
  Person = requires.clazz('person');
  DecoratorMw = requires.mw('decorator_mw');
  OrderedHash = require('jsclass/src/hash').OrderedHash;
  Decorations = requires.lib('decorations');
  CtxDecorations = requires.lib('context_decorations');
  describe('ContextDecorations', function(){
    var cds;
    cds = {};
    describe('create instance', function(){
      context('no args', function(){
        before(function(){
          return cds.empty = new CtxDecorations;
        });
        specify('has Hash registry', function(){
          return cds.empty.repository.constructor.should.eql(OrderedHash);
        });
        return specify('has no keys', function(){
          return expect(cds.empty.repository.keys().length).to.equal(0);
        });
      });
      return context('with hash', function(){
        before(function(){
          return cds.basic = new CtxDecorations({
            x: 1,
            y: 2
          });
        });
        specify('has Hash registry', function(){
          return cds.basic.repository.constructor.should.equal(OrderedHash);
        });
        return describe('repository', function(){
          specify('has 2 keys', function(){
            return expect(cds.basic.repository.keys().length).to.equal(2);
          });
          specify('repo x = 1', function(){
            return expect(cds.basic.find('x')).to.equal(1);
          });
          return specify('repo y = 2', function(){
            return expect(cds.basic.find('y')).to.equal(2);
          });
        });
      });
    });
    xdescribe('get', function(){
      return context('empty repo', function(){
        before(function(){
          return cds.empty = new CtxDecorations;
        });
        return specify('x not found', function(){
          return expect(dcs.empty.find('x')).to.equal(void 8);
        });
      });
    });
    return xdescribe('set', function(){
      return context('repo x = 2', function(){
        before(function(){
          cds.setme = new CtxDecorations;
          return cds.setme.register('x', 2);
        });
        return specify('x is found', function(){
          return expect(cds.setme.find('x')).to.equal(2);
        });
      });
    });
  });
}).call(this);
