// Generated by LiveScript 1.2.0
(function(){
  var requires, assert, expect, _, Person, DecoratorMw, OrderedHash, Decorations, CtxDecorations;
  requires = require('../../requires');
  requires.test('test_setup');
  assert = require('chai').assert;
  expect = require('chai').expect;
  _ = require('prelude-ls');
  Person = requires.clazz('person');
  DecoratorMw = requires.mw('decorator_mw');
  OrderedHash = require('jsclass/src/hash').OrderedHash;
  Decorations = requires.lib('decorations');
  CtxDecorations = requires.lib('context_decorations');
  describe('ContextDecorations', function(){
    var cds, dcs;
    cds = {};
    dcs = {};
    describe('create instance', function(){
      context('no args', function(){
        before(function(){
          return cds.empty = new CtxDecorations;
        });
        specify('has Hash registry', function(){
          return cds.empty.repository.constructor.should.eql(OrderedHash);
        });
        return specify('has no keys', function(){
          return expect(cds.empty.repository.keys().length).to.equal(0);
        });
      });
      return context('with hash', function(){
        before(function(){
          var xRepo;
          xRepo = new Decorations({
            'x': function(){
              return '1';
            },
            y: function(){
              return '2';
            }
          });
          return cds.basic = new CtxDecorations({
            'default': xRepo
          });
        });
        specify('has Hash registry', function(){
          return cds.basic.repository.constructor.should.equal(OrderedHash);
        });
        return describe('repository', function(){
          specify('has 2 keys', function(){
            return expect(cds.basic.repository.keys().length).to.equal(1);
          });
          specify('repo x = 1', function(){
            return expect(cds.basic.find('x')()).to.equal('1');
          });
          return specify('repo y = 2', function(){
            return expect(cds.basic.find('y')()).to.equal('2');
          });
        });
      });
    });
    describe('get', function(){
      return context('empty repo', function(){
        before(function(){
          return cds.empty = new CtxDecorations;
        });
        return specify('x not found', function(){
          return expect(cds.empty.find('x')).to.equal(null);
        });
      });
    });
    return describe('set', function(){
      return context('repo x = 2', function(){
        before(function(){
          cds.setme = new CtxDecorations;
          dcs.person = new Decorations({
            'person': function(){
              return 'Person';
            }
          });
          return cds.setme.register('x', dcs.person);
        });
        return specify('x is found', function(){
          return expect(cds.setme.find('x')).to.equal(dcs.person);
        });
      });
    });
  });
}).call(this);
